In [1]:
import pandas as pd
import numpy as np

In [6]:
calendar = pd.read_csv('./seattle/calendar.csv')
listings = pd.read_csv('./seattle/listings.csv')
reviews = pd.read_csv('./seattle/reviews.csv')

# Calendar 

In [11]:
calendar.head()

listing_id        date available   price
0      241032  2016-01-04         t  $85.00
1      241032  2016-01-05         t  $85.00
2      241032  2016-01-06         f     NaN
3      241032  2016-01-07         f     NaN
4      241032  2016-01-08         f     NaN

In [30]:
calendar.dtypes

listing_id             int64
date          datetime64[ns]
available             object
price                 object
dtype: object

In [29]:
calendar['date'] = pd.to_datetime(calendar['date'], format = '%Y-%m-%d')

In [45]:
#check if all listing ids have the same number of dates

count_dates = calendar[['listing_id','date']].groupby('listing_id').count()
count_dates['date'].unique()

array([365], dtype=int64)

In [49]:
calendar.available.unique()

array([1, 0], dtype=int64)

In [52]:
# replace 'available' column data with numeric binary data
try:
    calendar['available'] = calendar['available'].replace({'t':1,'f':0})
except:
    pass
calendar.available.unique()

array([1, 0], dtype=int64)

In [54]:
calendar[['listing_id','available']].groupby('listing_id').mean()

available
listing_id           
3335         0.846575
4291         1.000000
5682         0.846575
6606         1.000000
7369         0.145205
9419         1.000000
9460         0.156164
9531         0.493151
9534         0.717808
9596         0.994521
10385        1.000000
10695        1.000000
11012        1.000000
11411        1.000000
13068        0.942466
14386        0.865753
15108        0.838356
17951        0.841096
19611        0.413699
19619        0.375342
19623        0.471233
20868        0.980822
20927        0.934247
20928        0.915068
23192        0.931507
23356        0.895890
23430        0.432877
23919        0.868493
24212        0.394521
25002        0.843836
...               ...
10234558     0.972603
10235014     0.008219
10235136     0.002740
10247453     0.991781
10248139     0.093151
10249527     0.019178
10250735     0.010959
10252110     0.052055
10262971     1.000000
10265391     0.991781
10267360     0.241096
10272763     1.000000
10273158     0.964384
10274175     0.945205
10279830     0.923288
10281965     0.975342
10292753     0.416438
10295151     0.978082
10299108     0.178082
10299195     0.038356
10309898     1.000000
10310373     0.961644
10318171     0.997260
10319529     0.002740
10331249     0.969863
10332096     1.000000
10334184     0.989041
10339144     0.000000
10339145     1.000000
10340165     0.980822

[3818 rows x 1 columns]

# Reviews

In [8]:
reviews.head()

listing_id        id        date  reviewer_id reviewer_name  \
0     7202016  38917982  2015-07-19     28943674        Bianca   
1     7202016  39087409  2015-07-20     32440555         Frank   
2     7202016  39820030  2015-07-26     37722850           Ian   
3     7202016  40813543  2015-08-02     33671805        George   
4     7202016  41986501  2015-08-10     34959538          Ming   

                                            comments  
0  Cute and cozy place. Perfect location to every...  
1  Kelly has a great room in a very central locat...  
2  Very spacious apartment, and in a great neighb...  
3  Close to Seattle Center and all it has to offe...  
4  Kelly was a great host and very accommodating ...

In [55]:
listings.shape

(3818, 92)